name: Smab_Dashboard_CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build & push backend
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./dashboard_backend
          file: ./dashboard_backend/Dockerfile
          push: true
          tags: aminegha10/smab_emaildashboard_fullstack-backend:latest

      # Build & push frontend
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./dashboard_frontend
          file: ./dashboard_frontend/Dockerfile
          push: true
          tags: aminegha10/smab_emaildashboard_fullstack-frontend:latest
